<a href="https://colab.research.google.com/github/NonMundaneDev/AWS-Cloud-ML-Udacity-Practice/blob/master/Optimizing_Code_Holiday_Gifts_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Optimizing Code: Holiday Gifts Data

In [0]:
import time
import numpy as np

In [0]:
with open('gift_costs.txt') as f:
    gift_costs = f.read().split('\n')
    
gift_costs = np.array(gift_costs).astype(int)  # convert string to int

In [5]:
gift_costs

array([ 8, 84, 42, ..., 51, 54,  2])

Say your online gift store has one million users that each listed a gift on a wish list. You have the prices for each of these gifts stored in `gift_costs.txt`. For the holidays, you're going to give each customer their wish list gift for free if it is under 25 dollars. Now, you want to calculate the total cost of all gifts under 25 dollars to see how much you'd spend on free gifts. Here's one way you could've done it...

CLUNKY CODE:


In [6]:
start = time.time()

total_price = 0
for cost in gift_costs:
    if cost < 25:
        total_price += cost * 1.08  # add cost after tax

print(total_price)
print('Duration: {} seconds'.format(time.time() - start))

3546337.6799999964
Duration: 0.960162878036499 seconds


## Refactored Code

In [15]:
gift_costs < 25

array([ True, False, False, ..., False, False,  True])

In [16]:
gift_costs[gift_costs < 25]

array([ 8, 23, 22, ..., 12, 13,  2])

In [14]:
## Using numpy's handy np.sum function

start = time.time()

total_price =  np.sum(gift_costs[gift_costs < 25]) * 1.08

print(total_price)
print('Duration: {} seconds'.format(time.time() - start))

3546337.68
Duration: 0.011751413345336914 seconds


In [24]:
print("{} Seconds.".format(0.960162878036499 - 0.011751413345336914))

0.9484114646911621 Seconds.


Significant boost in performance!